#!/usr/bin/env python3
"""Writes IssueReportChannels.Build.g.cs from DISCORD_ISSUE_WEBHOOK_URL (or empty)."""

from __future__ import annotations

import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "src/presentation/support/IssueReportChannels.Build.g.cs"


def escape_csharp_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def main() -> None:
    url = os.environ.get("DISCORD_ISSUE_WEBHOOK_URL", "").strip()
    escaped = escape_csharp_string(url)
    OUTPUT.write_text(
        f"""// <auto-generated> Run via MSBuild before compile; do not edit.

namespace GrimSpace.Presentation.Support;

internal static partial class IssueReportChannels
{{
    internal const string DiscordWebhookUrl = "{escaped}";
}}
""",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
