// <auto-generated> Run via MSBuild before compile; do not edit.

namespace GrimSpace.Presentation.Support;

internal static partial class IssueReportChannels
{
    internal const string DiscordWebhookUrl = "";
}
